import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import "animate.css";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import localFont from "next/font/local";
import Footer from "@/components/base/footer";

const GraphikFont = localFont({
  src: [
    {
      path: "./Graphik-Regular-Trial.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "./Graphik-Medium-Trial.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "./Graphik-Bold-Trial.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  adjustFontFallback: "Arial",
  display: "swap",
  fallback: ["Helvetica", "Arial", "sans-serif"],
  preload: true,
  variable: "--font-graphik",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${GraphikFont.className} antialiased`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
